/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import bill.connectiondb;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class delete_product extends javax.swing.JFrame {

    /**
     * Creates new form delete_product
     */
    public delete_product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_pId = new javax.swing.JLabel();
        lbl_product_name = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        lbl_activate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_pId = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        txt_product_name = new javax.swing.JTextField();
        txt_rate = new javax.swing.JTextField();
        txt_description = new javax.swing.JTextField();
        txt_activate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btn_delete = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Delete Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 37, 190, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 580, 10));

        lbl_pId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_pId.setText("Product ID");
        getContentPane().add(lbl_pId, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 104, -1, -1));

        lbl_product_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_product_name.setText("Product Name");
        getContentPane().add(lbl_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 183, -1, -1));

        lbl_rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rate.setText("Rate");
        getContentPane().add(lbl_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 235, -1, -1));

        lbl_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_description.setText("Description");
        getContentPane().add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 281, -1, -1));

        lbl_activate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_activate.setText("Activate");
        getContentPane().add(lbl_activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 330, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 590, 10));

        txt_pId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_pId, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 103, 171, -1));

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        txt_product_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 182, 250, -1));

        txt_rate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 235, 250, -1));

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 287, 250, -1));

        txt_activate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 326, 250, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 580, 10));

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(51, 0, 51));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 399, -1, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(51, 0, 51));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 399, -1, -1));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(51, 0, 51));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 399, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new delete_product().setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String pId=txt_pId.getText();
        try
        {
            Connection conn=connectiondb.getCon();
            Statement stat=conn.createStatement();
            ResultSet res=stat.executeQuery("select * from product where pId='"+pId+"'");
            
            if(res.next())
            {
                txt_product_name.setText(res.getString(2));
                txt_rate.setText(res.getString(3));
                txt_description.setText(res.getString(4));
                txt_activate.setText(res.getString(5));
                txt_pId.setEditable(false);
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Product does not exists");
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String pId=txt_pId.getText();
        int c = JOptionPane.showConfirmDialog(null,"Do you want to delete?","select",JOptionPane.YES_NO_OPTION);
        if (c==0)
        {
            try
            {
                Connection conn=connectiondb.getCon();
                Statement stat=conn.createStatement();
                stat.executeUpdate("delete from product whwre pId='"+pId+"'");
                setVisible(false);
                new delete_product().setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new delete_product().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_activate;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_pId;
    private javax.swing.JLabel lbl_product_name;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JTextField txt_activate;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_pId;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_rate;
    // End of variables declaration//GEN-END:variables
}
