/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import bill.connectiondb;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class final_bill extends javax.swing.JFrame {
    public int finalTotal=0;
  

    /**
     * Creates new form final_bill
     */
    public final_bill() {
        initComponents();
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
        Date dt=new Date();
        lbl_date.setText(df.format(dt));
        
        DateTimeFormatter ft= DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime nw=LocalDateTime.now();
        lbl_time.setText(ft.format(nw));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lbl_product_name = new javax.swing.JLabel();
        txt_product_name = new javax.swing.JTextField();
        lbl_rate = new javax.swing.JLabel();
        txt_rate = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        lbl_qty = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        lbl_product_id = new javax.swing.JLabel();
        txt_product_id = new javax.swing.JTextField();
        btn_add_product = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_total = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        lbl_paid = new javax.swing.JLabel();
        lbl_return = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_paid = new javax.swing.JTextField();
        txt_return = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 188, 121));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Bill");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 32, 95, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1166, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Product Details -:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 129, -1, -1));

        lbl_product_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_product_name.setText("Product Name");
        getContentPane().add(lbl_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        txt_product_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 150, -1));

        lbl_rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rate.setText("Rate");
        getContentPane().add(lbl_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, -1));

        txt_rate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 120, -1));

        lbl_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_description.setText("Description");
        getContentPane().add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 150, -1));

        lbl_qty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_qty.setText("Quantity");
        getContentPane().add(lbl_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        txt_qty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 92, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 1166, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setText("Date-:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 51));
        jLabel11.setText("Time-:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));
        getContentPane().add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 26, 110, 30));
        getContentPane().add(lbl_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 90, 30));

        lbl_product_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_product_id.setText("Product ID");
        getContentPane().add(lbl_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txt_product_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_product_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 76, -1));

        btn_add_product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add_product.setForeground(new java.awt.Color(0, 0, 153));
        btn_add_product.setText("Add");
        btn_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_productActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        tbl_total.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_total);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 299, 600, 240));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText("Calculation Details-:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_total.setText("Total");
        getContentPane().add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, -1, -1));

        lbl_paid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_paid.setText("Paid Amount");
        getContentPane().add(lbl_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        lbl_return.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_return.setText("Return Amount");
        getContentPane().add(lbl_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 150, -1));

        txt_paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paidActionPerformed(evt);
            }
        });
        getContentPane().add(txt_paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 150, -1));
        getContentPane().add(txt_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 150, -1));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(0, 0, 153));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 360, -1, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 0, 153));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, -1, -1));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(0, 0, 153));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_product_idActionPerformed
        // TODO add your handling code here:
        String pId=txt_product_id.getText();
        try
        {
            Connection con=connectiondb.getCon();
            Statement stat=con.createStatement();
            ResultSet re=stat.executeQuery("select *from product where pId='"+pId+"'");
            if(re.next())
            {
                txt_product_name.setText(re.getString(2));
                txt_rate.setText(re.getString(3));
                txt_qty.setText("1");
                txt_description.setText(re.getString(4));
            }
            else
            {
                txt_product_name.setText("");
                txt_rate.setText("");
                txt_qty.setText("");
                txt_description.setText("");
            }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_txt_product_idActionPerformed

    private void btn_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_productActionPerformed
        // TODO add your handling code here:
        int price=Integer.parseInt(txt_rate.getText());
        int quantity=Integer.parseInt(txt_qty.getText());
        int total=price*quantity;
        DefaultTableModel mod=(DefaultTableModel)tbl_total.getModel();
        mod.addRow(new Object[]{txt_product_name.getText(),txt_description.getText(),price,quantity,total});
        finalTotal=finalTotal+total;
        String al1=String.valueOf(finalTotal);
        txt_total.setText(al1);
    }//GEN-LAST:event_btn_add_productActionPerformed

    private void txt_paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paidActionPerformed
        // TODO add your handling code here:
        String paid=txt_paid.getText();
        int x=Integer.parseInt(paid);
        finalTotal=x-finalTotal;
        String all=String.valueOf(finalTotal);
        txt_return.setText(all);
        txt_return.setEditable(false);
        
    }//GEN-LAST:event_txt_paidActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new final_bill().setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String pId = txt_product_id.getText();
        String pName = txt_product_name.getText();
        String rate = txt_rate.getText();
        String description = txt_description.getText();
        
        
        try
        {
           Connection conn = connectiondb.getCon();
           Statement stat = conn.createStatement();
           stat.executeUpdate("insert into product values('"+pId+"','"+pName+"','"+rate+"','"+description+"')");
           JOptionPane.showMessageDialog(null, "Successfully Saved!");
           setVisible(false);
           new new_product().setVisible(true);
           
           
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(final_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(final_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(final_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(final_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new final_bill().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_product;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_paid;
    private javax.swing.JLabel lbl_product_id;
    private javax.swing.JLabel lbl_product_name;
    private javax.swing.JLabel lbl_qty;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JLabel lbl_return;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tbl_total;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_paid;
    private javax.swing.JTextField txt_product_id;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_rate;
    private javax.swing.JTextField txt_return;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
