/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import bill.connectiondb;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class new_product extends javax.swing.JFrame {

    /**
     * Creates new form new_product
     */
    public new_product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        lbl_product_id = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_product_name = new javax.swing.JLabel();
        lbl_rate = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        lbl_activate = new javax.swing.JLabel();
        txt_product_name = new javax.swing.JTextField();
        txt_rate = new javax.swing.JTextField();
        txt_description = new javax.swing.JTextField();
        cmb_activate = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        btn_save = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_pId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 160));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, 600, 10));

        lbl_product_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_product_id.setText("Product ID");
        getContentPane().add(lbl_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 107, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 610, 10));

        lbl_product_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_product_name.setText("Product Name");
        getContentPane().add(lbl_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 181, -1, -1));

        lbl_rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rate.setText("Rate");
        getContentPane().add(lbl_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 228, -1, -1));

        lbl_description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_description.setText("Description");
        getContentPane().add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 277, -1, -1));

        lbl_activate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_activate.setText("Activate");
        getContentPane().add(lbl_activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 324, -1, -1));

        txt_product_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_product_name.setForeground(new java.awt.Color(153, 153, 153));
        txt_product_name.setText("Enter Product Name");
        txt_product_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_product_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_product_nameFocusLost(evt);
            }
        });
        txt_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_product_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 180, 250, -1));

        txt_rate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_rate.setForeground(new java.awt.Color(153, 153, 153));
        txt_rate.setText("Enter Rate");
        txt_rate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_rateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rateFocusLost(evt);
            }
        });
        getContentPane().add(txt_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 227, 250, -1));

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_description.setForeground(new java.awt.Color(153, 153, 153));
        txt_description.setText("Enter Description");
        txt_description.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_descriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_descriptionFocusLost(evt);
            }
        });
        getContentPane().add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 276, 250, -1));

        cmb_activate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_activate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YES", "NO" }));
        getContentPane().add(cmb_activate, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 323, 250, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, 600, 10));

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(51, 0, 51));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 411, -1, -1));

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(51, 0, 51));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 411, -1, -1));

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(51, 0, 51));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 411, -1, -1));

        lbl_pId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_pId.setForeground(new java.awt.Color(0, 0, 255));
        lbl_pId.setText("1");
        getContentPane().add(lbl_pId, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 103, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("New Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -40, 1650, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            Connection conn = connectiondb.getCon();
            Statement stat = conn.createStatement();
            ResultSet res = stat.executeQuery("select max (pId) from product");

            if (res.first()) {
                int id = res.getInt(1);
                id = id + 1;
                String str = String.valueOf(id);
                lbl_pId.setText(str);
            } else {
                lbl_pId.setText("1");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void txt_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_product_nameActionPerformed

    private void txt_product_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_product_nameFocusGained
        // TODO add your handling code here:
        if (txt_product_name.getText().equals("Enter Product Name")) {
            txt_product_name.setText("");
            txt_product_name.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_product_nameFocusGained

    private void txt_product_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_product_nameFocusLost
        // TODO add your handling code here:
        if (txt_product_name.getText().equals("")) {
            txt_product_name.setText("Enter Product Name");
            txt_product_name.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_product_nameFocusLost

    private void txt_rateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rateFocusGained
        // TODO add your handling code here:
        if (txt_rate.getText().equals("Enter Rate")) {
            txt_rate.setText("");
            txt_rate.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_rateFocusGained

    private void txt_rateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rateFocusLost
        // TODO add your handling code here:
        if (txt_rate.getText().equals("Enter Rate")) {
            txt_rate.setText("Enter Rate");
            txt_rate.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_rateFocusLost

    private void txt_descriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_descriptionFocusGained
        // TODO add your handling code here:
        if (txt_description.getText().equals("Enter Description")) {
            txt_description.setText("");
            txt_description.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txt_descriptionFocusGained

    private void txt_descriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_descriptionFocusLost
        // TODO add your handling code here:
        if (txt_description.getText().equals("Enter Description")) {
            txt_description.setText("");
            txt_description.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txt_descriptionFocusLost

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
         String pId = lbl_pId.getText();
        String pName = txt_product_name.getText();
        String rate = txt_rate.getText();
        String description = txt_description.getText();
        String activate = (String) cmb_activate.getSelectedItem();
        
        try
        {
           Connection conn = connectiondb.getCon();
           Statement stat = conn.createStatement();
           stat.executeUpdate("insert into product values('"+pId+"','"+pName+"','"+rate+"','"+description+"','"+activate+"')");
           JOptionPane.showMessageDialog(null, "Successfully Saved!");
           setVisible(false);
           new new_product().setVisible(true);
           
           
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new new_product().setVisible(true);
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new new_product().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_activate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_activate;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_pId;
    private javax.swing.JLabel lbl_product_id;
    private javax.swing.JLabel lbl_product_name;
    private javax.swing.JLabel lbl_rate;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_rate;
    // End of variables declaration//GEN-END:variables

    private static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
